FROM python:3.11-slim

WORKDIR /app

# Instala dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia o gateway
COPY sensor_gateway.py .

CMD ["python", "sensor_gateway.py"]
