FROM ruby:3.2

WORKDIR /app

COPY cron_worker/Gemfile cron_worker/Gemfile.lock ./

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN gem install bundler
RUN bundle config set path /usr/local/bundle
RUN bundle install

COPY cron_worker/Rakefile Rakefile
COPY cron_worker/models.rb models.rb
COPY cron_worker/.env .env
COPY cron_worker/lib lib

CMD ["bash", "-c", "while true; do echo '⏰ ['$(date '+%H:%M')'] Verificando agendamentos...'; bundle exec rake irrigation:run; sleep 60; done"]
