version: '3.8'

services:
  db:
    image: postgres:14
    container_name: iot_postgres
    restart: always
    environment:
      POSTGRES_USER: romao
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: IOT_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: iot_redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    container_name: iot_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data:
