default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] || "postgresql://admin123:admin123@localhost:5433/IOT_development" %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || "postgresql://admin123:admin123@localhost:5433/IOT_test" %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || "postgresql://admin123:admin123@localhost:5433/IOT_production" %>
