# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  sslmode: verify-full
  sslrootcert: <%= Rails.root.join("config/certs/supabase/prod-ca-2021.crt") %>
  prepared_statements: <%= ENV["PGBOUNCER"] == "1" ? false : true %>

development:
  <<: *default
  host: <%= ENV.fetch("PGHOST", "aws-0-eu-north-1.pooler.supabase.com") %>
  port: <%= ENV.fetch("PGPORT", 6543) %>
  database: <%= ENV.fetch("PGDATABASE", "postgres") %>
  # ATENÇÃO: o utilizador no pooler inclui o project ref
  username: <%= ENV.fetch("PGUSER", "postgres.zevycgeskisrcevlvgdb") %>
  password: <%= ENV.fetch("PGPASSWORD") %>

test:
  <<: *default
  host: <%= ENV.fetch("PGHOST", "aws-0-eu-north-1.pooler.supabase.com") %>
  port: <%= ENV.fetch("PGPORT", 6543) %>
  database: <%= ENV.fetch("PGDATABASE_TEST", "postgres") %>
  username: <%= ENV.fetch("PGUSER", "postgres.zevycgeskisrcevlvgdb") %>
  password: <%= ENV.fetch("PGPASSWORD") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %> # usa o URL do pooler na produção
